package com.cikarastudio.cikarajantungdesafix;

public class mentahan {

//            "rt_id": 1,
//            "nik": "3206165488906543",
//            "nama_penduduk": "Alfi Letari",
//            "status_ktp": "ktp-el",
//            "status_rekam": "belum rekam",
//            "id_card": null,
//            "kk_sebelum": "085667890332",
//            "hubungan_keluarga": "anak",
//            "jk": "perempuan",
//            "agama": "islam",
//            "status_penduduk": "tetap",
//            "no_akta": "789963467389",
//            "tempat_lahir": "Tasikmalaya",
//            "tgl_lahir": "2000-08-22",
//            "waktu_lahir": null,
//            "tempat_dilahirkan": "rumah",
//            "jenis_kelahiran": "tunggal",
//            "anak_ke": 1,
//            "penolong_kelahiran": "bidan perawat",
//            "berat_lahir": "3000",
//            "panjang_lahir": "42",
//            "pendidikan_kk": "slta/sederajat",
//            "pendidikan_tempuh": "sedang slta/sederajat",
//            "pekerjaan": "belum/tidak bekerja",
//            "status_warganegara": "wni",
//            "nomor_paspor": null,
//            "tgl_akhirpaspor": null,
//            "nomor_kitas": null,
//            "nik_ayah": "320616500432156",
//            "nama_ayah": "yusuf",
//            "nik_ibu": "32061657899653",
//            "nama_ibu": "dira",
//            "lat_penduduk": null,
//            "long_penduduk": null,
//            "no_telp": "0856672345167",
//            "email": "alfii@gmail.com",
//            "alamat_sebelum": "garut",
//            "alamat_sekarang": "jakarta",
//            "status_perkawinan": "belum kawin",
//            "no_bukunikah": null,
//            "tgl_perkawinan": null,
//            "akta_perceraian": null,
//            "tgl_perceraian": null,
//            "golongan_darah": "A",
//            "cacat": "TIDAK CACAT",
//            "sakit_menahun": "tidak ada/tidak sakit",
//            "akseptor_kb": "LAINNYA",
//            "asuransi": "asuransi lainnya",
}
